name: FitBot (cloud)

on:
  schedule:
    - cron: "55 7 * * 1-5"
    - cron: "00 8 * * 1-5"
    - cron: "05 8 * * 1-5"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Preparar booking-goals (JSON válido)
        run: |
          echo '${{ secrets.BOOKING_GOALS }}' > goals.json
          echo "Goals.json:"
          cat goals.json

      - name: Diagnóstico HTTP 403 (curl)
        run: |
          echo "Sin proxy:"
          curl -I -s -o /dev/null -w "%{http_code}\n" https://aimharder.com/login || true
          echo "Con proxy:"
          curl -I -s -o /dev/null -w "%{http_code}\n" -x "${{ secrets.PROXY }}" https://aimharder.com/login || true

      - name: Ejecutar fitbot sobreescribiendo entrypoint
        run: |
          docker run --rm \
            --entrypoint uv \
            pablobuenaposada/fitbot:latest \
            run python src/main.py \
              --email="${{ secrets.EMAIL }}" \
              --password="${{ secrets.PASSWORD }}" \
              --booking-goals="$(cat goals.json)" \
              --box-name="${{ secrets.BOX_NAME }}" \
              --box-id="${{ secrets.BOX_ID }}" \
              --days-in-advance="${{ secrets.DAYS_IN_ADVANCE }}" \
              --proxy="${{ secrets.PROXY }}"
