name: FitBot (cloud)

on:
  schedule:
    # Horario en UTC. En Madrid ahora (septiembre) = UTC+2.
    # Ajusta estos cron a la hora real de apertura de tu box.
    - cron: "55 7 * * 1-5"   # 09:55 Madrid
    - cron: "00 8 * * 1-5"   # 10:00 Madrid
    - cron: "05 8 * * 1-5"   # 10:05 Madrid
  workflow_dispatch: {}       # Permite lanzarlo a mano ahora mismo

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Preparar booking-goals (JSON válido)
        run: |
          echo '${{ secrets.BOOKING_GOALS }}' > goals.json
          echo "Goals.json:"
          cat goals.json

      - name: Ejecutar fitbot (imagen oficial)
        run: |
          docker run --rm \
            -e email="${{ secrets.EMAIL }}" \
            -e password="${{ secrets.PASSWORD }}" \
            -e booking-goals="$(cat goals.json)" \
            -e box-name="${{ secrets.BOX_NAME }}" \
            -e box-id="${{ secrets.BOX_ID }}" \
            -e days-in-advance="${{ secrets.DAYS_IN_ADVANCE }}" \
            -e proxy="${{ secrets.PROXY }}" \
            pablobuenaposada/fitbot:latest
