name: FitBot (cloud)

on:
  schedule:
    # Horario en UTC. En Madrid ahora = UTC+2.
    # Ajusta estas horas a tu ventana real de apertura.
    - cron: "55 7 * * 1-5"   # 09:55 Madrid
    - cron: "00 8 * * 1-5"   # 10:00 Madrid
    - cron: "05 8 * * 1-5"   # 10:05 Madrid
  workflow_dispatch: {}       # <- Esto habilita el botón "Run workflow"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Mostrar versión de Docker (debug opcional)
        run: |
          docker --version

      - name: Preparar booking-goals (JSON válido)
        run: |
          echo '${{ secrets.BOOKING_GOALS }}' > goals.json
          echo "Goals.json:"
          cat goals.json

      # Ejecutamos la imagen oficial, pero:
      #  - sobrescribimos el entrypoint a 'uv'
      #  - lanzamos nosotros el comando 'run python src/main.py ...'
      # Así evitamos que el Makefile/entrypoint toquen el JSON.
      - name: Ejecutar fitbot sobreescribiendo entrypoint
        run: |
          docker run --rm \
            --entrypoint uv \
            pablobuenaposada/fitbot:latest \
            run python src/main.py \
              --email="${{ secrets.EMAIL }}" \
              --password="${{ secrets.PASSWORD }}" \
              --booking-goals="$(cat goals.json)" \
              --box-name="${{ secrets.BOX_NAME }}" \
              --box-id="${{ secrets.BOX_ID }}" \
              --days-in-advance="${{ secrets.DAYS_IN_ADVANCE }}"
