jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Preparar booking-goals (JSON válido)
        run: |
          echo '${{ secrets.BOOKING_GOALS }}' > goals.json
          echo "Goals.json:"
          cat goals.json

      # Ejecutamos la imagen, pero
      #  - sobrescribimos el entrypoint a 'uv'
      #  - lanzamos nosotros el comando 'run python src/main.py ...'
      # Así evitamos que el Makefile/entrypoint toquen el JSON.
      - name: Ejecutar fitbot sobreescribiendo entrypoint
        run: |
          docker run --rm \
            --entrypoint uv \
            pablobuenaposada/fitbot:latest \
            run python src/main.py \
              --email="${{ secrets.EMAIL }}" \
              --password="${{ secrets.PASSWORD }}" \
              --booking-goals="$(cat goals.json)" \
              --box-name="${{ secrets.BOX_NAME }}" \
              --box-id="${{ secrets.BOX_ID }}" \
              --days-in-advance="${{ secrets.DAYS_IN_ADVANCE }}"
