name: FitBot (cloud)

on:
  schedule:
    - cron: "55 7 * * 1-5"   # 09:55 Madrid (07:55 UTC)
    - cron: "00 8 * * 1-5"   # 10:00 Madrid (08:00 UTC)
    - cron: "05 8 * * 1-5"   # 10:05 Madrid (08:05 UTC)
  workflow_dispatch: {}       # Botón "Run workflow"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Preparar booking-goals (JSON válido)
        run: |
          echo '${{ secrets.BOOKING_GOALS }}' > goals.json
          python - <<'PY'
import json
j = open('goals.json','r',encoding='utf-8').read()
json.loads(j)
print("OK: goals.json es JSON válido")
PY

      - name: Diagnóstico HTTP (comprobar 403 vs 200)
        run: |
          echo "Sin proxy -> código HTTP:"
          curl -I -s -o /dev/null -w "%{http_code}\n" https://aimharder.com/login || true
          echo "Con proxy -> código HTTP:"
          if [ -n "${{ secrets.PROXY }}" ]; then
            curl -I -s -o /dev/null -w "%{http_code}\n" -x "${{ secrets.PROXY }}" https://aimharder.com/login || true
          else
            echo "No hay PROXY definido"
          fi

      - name: Ejecutar fitbot con proxy (entrypoint uv)
        run: |
          docker run --rm \
            --entrypoint uv \
            -e HTTP_PROXY="${{ secrets.PROXY }}" \
            -e HTTPS_PROXY="${{ secrets.PROXY }}" \
            -e http_proxy="${{ secrets.PROXY }}" \
            -e https_proxy="${{ secrets.PROXY }}" \
            pablobuenaposada/fitbot:latest \
            run python src/main.py \
              --email="${{ secrets.EMAIL }}" \
              --password="${{ secrets.PASSWORD }}" \
              --booking-goals="$(cat goals.json)" \
              --box-name="${{ secrets.BOX_NAME }}" \
              --box-id="${{ secrets.BOX_ID }}" \
              --days-in-advance="${{ secrets.DAYS_IN_ADVANCE }}" \
              --proxy="${{ secrets.PROXY }}"
